### PR TITLE
Adding mention of how to find the aegir_server_ip.

### PR DESCRIPTION
**Pull request by jonpugh**
I found it challenging to find out the IP address that the aegir master server is using to connect to the remote mysql server.

Let's add instructions for discovering this IP.

### CODE REVIEW

**Comment by jonpugh** [comment]
I've changed this from the "mysql -u intntlly" command to tell users to check $SSH_CLIENT environment variable.

Not sure if one is better than the other, but SSH seemed like an easier way to go since the user will already have SSH access.

**Comment by helmo** [comment]
Sorry, but that does not work. You need to use single quotes to prevent the client from evaluating the $SSH_CLIENT before making the ssh connection.

Why do you add the '-C' option for compression?

**Comment by formatCvt** [comment]
agree about single quotes, also command can be
ssh aegir@remote_host 'echo $SSH_CLIENT | cut -d " " -f 1'

**Comment by jonpugh** [comment]
I guess this could vary depending on the shell...

The capital C is to run the command.

I could change it to just say " SSH in and run 'echo $SSH_CLIENT'"?

**Comment by helmo** [comment]
On 22-07-15 14:56, Jon Pugh wrote:

> I guess this could vary depending on the shell...
> 
> The capital C is to run the command.

Not according to the manpages on my Debian systems...

> I could change it to just say " SSH in and run 'echo $SSH_CLIENT'"?

Yes that might be safer.

## 

Met vriendelijke groet / Regards,

Herman van Rink
Initfour websolutions

**Comment by jonpugh** [comment]
Strange, on ubuntu 14, this works...

```
aegir@devshop:~$ ssh root@devshop.remote -C 'echo test'
test
```

**Comment by helmo** [comment]
Sure, but it would also work without the -C option.

**Comment by formatCvt** [comment]
"-C      Requests compression of all data (including stdin, stdout, stderr, and data for forwarded X11 and TCP connections)." from man ssh

**Comment by cweagans** [comment]
This PR needs rerolled against the `3.x` branch (we just moved some things around to prepare for Aegir 4 docs).

**Pull request closed without merging**
