### PR TITLE
Adding instructions for hardening and modernizing your SSL configuration

### PR DESCRIPTION
**Pull request by jonpugh**
I am documenting my findings when having to secure a server properly.

Included an example for Ubuntu 14.04 apache.  We should probably include the NGINX configuration as well?

@memtkmcc would you mind helping me on adding proper NGINX SSL config?

### CODE REVIEW

**Comment by colans** [comment]
I'm tempted to reject this because we're providing the config in [Aegir HTTPS](https://gitlab.com/aegir/hosting_https).  It's not something that users can easily change; it's managed by Aegir.  So let's come up with secure defaults, and make it configurable.  See [Secure Sites do not pass security scanning software](https://gitlab.com/aegir/hosting_https/issues/38) for details.

**Comment by jonpugh** [comment]
I'm not seeing any of those settings in hosting_https template files...

Am I missing something?  SSLCipherSuite and the rest are only in apache's ssl.conf file?

**Comment by colans** [comment]
Nginx ones are in https://gitlab.com/aegir/hosting_https/tree/master/submodules/nginx_https/drush/Provision/Config/Nginx/Https .  Assuming Apache is the same, these settings aren't explicitly in there so it's going with the defaults.  We'd need to add these as @memtkmcc is doing for BOA (and then make them configurable (but this part can be done later, IMHO).

**Comment by helmo** [comment]
+1 to merge... although that whole page should be re-written with hosting_https in mind.

**Comment by colans** [comment]
Merging for now, as it's better than what was there before, but let's continue the discussion at [Secure Sites do not pass security scanning software](https://www.drupal.org/project/hosting_https/issues/2936051).

Added note over there about updating the docs.

**Comment by colans** [comment]
As this repo is being archived, I applied the patch to the GitLab repo.  This one is no longer maintained.

**Pull request closed without merging**
