### PR TITLE
[WIP] Start a Golden contrib module guidelines section

### PR DESCRIPTION
**Pull request by helmo**
Nothing final ... but the start of a discussion what we want in.

I think these should be easy to meet for the yesterday suggested hosting_logs, hosting_https and aegir_ssh

### CODE REVIEW

**Review by ergonlogic — COMMENTED** [review]
First off, thanks for working on this.

It might be worthwhile to link to http://docs.aegirproject.org/en/3.x/extend/contrib/#golden-contrib, and vice versa. That'd make it easier for users to understand what's included in the project and why.

I think the first two items in the guidelines could be merged, because they're both essentially about having a proper release.

I suggest pointing to http://docs.aegirproject.org/en/3.x/community/core-team/#current-members, rather the Hostmaster project, since the latter includes a bunch of inactive contributors. I make a habit of adding all current maintainers to any project under consideration for Golden Contrib, so 2 seems like a small number. But I don't object to it, if others feel it's sufficient.

I think it might be worthwhile to add a point outlining a security policy (e.g., "needs security review by maintainers", "should not increase the system's attack surface", etc.) Although this might need broader discussion.

Finally, a minor grammar fix: "At least" is 2 words.

**Comment by colans** [comment]
> It might be worthwhile to link to http://docs.aegirproject.org/en/3.x/extend/contrib/#golden-contrib, and vice versa. That'd make it easier for users to understand what's included in the project and why.

Done.

> I think the first two items in the guidelines could be merged, because they're both essentially about having a proper release.

I disagree as it's possible to have a proper release, and not opt into security coverage.

> I suggest pointing to http://docs.aegirproject.org/en/3.x/community/core-team/#current-members, rather the Hostmaster project, since the latter includes a bunch of inactive contributors. I make a habit of adding all current maintainers to any project under consideration for Golden Contrib, so 2 seems like a small number. But I don't object to it, if others feel it's sufficient.

I rewrote this part.  Please review.

> I think it might be worthwhile to add a point outlining a security policy (e.g., "needs security review by maintainers", "should not increase the system's attack surface", etc.) Although this might need broader discussion.

I added a section for this.

> Finally, a minor grammar fix: "At least" is 2 words.

Fixed.

I also added an item:

> It should not encourage users to perform dangerous operations, from which there is no recovery.  If such features are requested, their use must come with warnings.

**Comment by colans** [comment]
Note: I used absolute links instead of relative ones as I'm not sure how to test those.  Please fix if possible.  My editor, Retext, is of no help here, and I can't get the official editor working locally.

**Comment by ergonlogic** [comment]
I meant something like:

> It should have a full release on Drupal.org that is covered by the security team.

**Comment by colans** [comment]
Sounds good to me.

**Comment by helmo** [comment]
+1 for adding proper warnings about security implications.

What about 'WARNING: this module grants shell access to the hostmaster admin.' in the description field of hosting.feature.aegir_ssh.inc

**Pull request merged**
