### PR TITLE
Adding section on "Customizing settings.php"

### PR DESCRIPTION
**Pull request by jonpugh**

### CODE REVIEW

**Comment by helmo** [comment]
Hmm, this duplicates part of the 'Injecting into settings.php' section lower in that file.

**Comment by jonpugh** [comment]
Ok, cleaned up a lot. I'm keeping **Customizing Settings.php** to the top, I think it's the most common thing people look for. I moved the cookie example out of the `local.settings.php` section and into the PHP.ini values section (which I renamed because it was confusing, I thought it meant PHP $Variables, not php settings.

Also removed duplication of example vhost hook.

**Comment by jonpugh** [comment]
This doesn't seem correct:

https://github.com/aegir-project/documentation/blob/customizing-settings/docs/extend/altering-behaviours.md#injecting-into-platform-wide-vhosts-htaccess

> As a result, Aegir disables the reading of the Drupal .htaccess in the runtime environment.

> This does not mean that the .htaccess is not needed. Instead, when you run the Verify task against a Platform, the .htaccess is studied by Aegir and its contents are copied into the platform-wide Apache vhost configuration, typically located in /var/aegir/config/server_master/apache/platform.d

My platform .conf files look like this:

```
# Include the platform's htaccess file
Include /var/aegir/devmaster-1.x/.htaccess

  # Do not read any .htaccess in the platform
  AllowOverride none
```

**Comment by helmo** [comment]
Looks good to go :)

Your correct in that the htaccess content is not copied... Apache includes it. Maybe it should also be clarified that it's only the htaccess in the root that get's included ... not just in any random subdir.

https://www.drupal.org/project/provision/issues/2778969 is related here.

**Pull request merged**
